spring.application.name=WearWise

spring.datasource.url=jdbc:mysql://localhost:3306/wearwise
spring.datasource.username=root
spring.datasource.password=Kaalu@1902

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=TSwg5ImnpJ/6oA+MNXBQQyJ9CJxg2YARIkwXgE2WZTs=
jwt.expiration=86400000


#  Gmail SMTP (OTP emails)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=wearwisetesting@gmail.com
spring.mail.password=lvdl frum wqqu bmfc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8